export const cities = [
	'Bratislava',
	'Košice',
	'Petržalka',
	'Prešov',
	'Žilina',
	'Banská Bystrica',
	'Nitra',
	'Trnava',
	'Trenčín',
	'Martin',
	'Poprad',
	'Prievidza',
	'Zvolen',
	'Považská Bystrica',
	'Michalovce',
	'Nové Zámky',
	'Spišská Nová Ves',
	'Komárno',
	'Humenné',
	'Levice',
	'Liptovský Mikuláš',
	'Bardejov',
	'Lučenec',
	'Piešťany',
	'Ružomberok',
	'Topoľčany',
	'Trebišov',
	'Čadca',
	'Dubnica nad Váhom',
	'Rimavská Sobota',
	'Pezinok',
	'Partizánske',
	'Dunajská Streda',
	'Vranov nad Topľou',
	'Šaľa',
	'Hlohovec',
	'Brezno',
	'Senica',
	'Nové Mesto nad Váhom',
	'Snina',
	'Senec',
	'Rožňava',
	'Žiar nad Hronom',
	'Dolný Kubín',
	'Bánovce nad Bebravou',
	'Púchov',
	'Malacky',
	'Handlová',
	'Kežmarok',
	'Stará Ľubovňa',
	'Sereď',
	'Kysucké Nové Mesto',
	'Galanta',
	'Skalica',
	'Levoča',
	'Detva',
	'Šamorín',
	'Sabinov',
	'Revúca',
	'Veľký Krtíš',
	'Myjava',
	'Zlaté Moravce',
	'Stupava',
	'Bytča',
	'Moldava nad Bodvou',
	'Holíč',
	'Nová Dubnica',
	'Svidník',
	'Fiľakovo',
	'Stropkov',
	'Kolárovo',
	'Štúrovo',
	'Banská Štiavnica',
	'Šurany',
	'Tvrdošín',
	'Veľké Kapušany',
	'Modra',
	'Stará Turá',
	'Krompachy',
	'Veľký Meder',
	'Smižany',
	'Vráble',
	'Sečovce',
	'Krupina',
	'Námestovo',
	'Vrútky',
	'Svit',
	'Turzovka',
	'Hriňová',
	'Liptovský Hrádok',
	'Kráľovský Chlmec',
	'Hnúšťa',
	'Hurbanovo',
	'Trstená',
	'Nová Baňa',
	'Šahy',
	'Bernolákovo',
	'Tornaľa',
	'Želiezovce',
	'Krásno nad Kysucou',
	'Spišská Belá',
	'Jarovnice',
	'Medzilaborce',
	'Lipany',
	'Turčianske Teplice',
	'Ivanka pri Dunaji',
	'Nemšová',
	'Žarnovica',
	'Sobrance',
	'Gelnica',
	'Beluša',
	'Vrbové',
	'Čaňa',
	'Rajec',
	'Oščadnica',
	'Dobšiná',
	'Poltár',
	'Chorvátský Grob',
	'Svätý Jur',
	'Raková',
	'Ilava',
	'Zákamenné',
	'Veľký Šariš',
	'Gabčíkovo',
	'Kremnica',
	'Sládkovičovo',
	'Lendak',
	'Skalité',
	'Tvrdošovce',
	'Gbely',
	'Čierny Balog',
	'Nesvady',
	'Dvory nad Žitavou',
	'Rabča',
	'Sliač',
	'Bojnice',
	'Veľké Čaníkovce',
	'Veľká Lomnica',
	'Brezová pod Bradlom',
	'Sučany',
	'Pavlovce nad Uhom',
	'Veľké Úľany',
	'Rudňany',
	'Valaliky',
	'Markušovce',
	'Čierne',
	'Strážske',
	'Komjatice',
	'Močenok',
	'Turany',
	'Medzev',
	'Cífer',
	'Palárikovo',
	'Šoporňa',
	'Teplička nad Váhom',
	'Nováky',
	'Trenčianska Teplá',
	'Veľké Zálužie',
	'Trenčianske Teplice',
	'Tisovec',
	'Leopoldov',
	'Giraltovce',
	'Cabaj-Čápor',
	'Bošany',
	'Terchová',
	'Vysoké Tatry',
	'Štiavnik',
	'Kanianka',
	'Rovinka',
	'Spišské Podhradie',
	'Lednické Rovne',
	'Kúty',
	'Borský Mikuláš',
	'Jelka',
	'Oravská Polhora',
	'Čachtice',
	'Podbrezová',
	'Varín',
	'Hanušovce nad Topľou',
	'Veľké Rovné',
	'Trstice',
	'Marcelová',
	'Valaská',
	'Bánov',
	'Veľká Ida',
	'Tešedíkovo',
	'Čierna nad Tisou',
	'Turna nad Bodvou',
	'Slovenský Grob',
	'Jasov',
	'Veľké Leváre',
	'Okoč',
	'Novoť',
	'Tlmače',
	'Svrčinovec',
	'Spišské Vlachy',
	'Bystrany',
	'Zborov',
	'Štrba',
	'Oravská Lesná',
	'Nálepkovo',
	'Horná Súča',
	'Ľubotice',
	'Smolenice',
	'Belá nad Cirochou',
	'Trenčianska Turná',
	'Malinovo',
	'Prakovce',
	'Neded',
	'Bátorove Kosihy',
	'Horné Saliby',
	'Slovenská Ľupča',
	'Nitrianske Pravno',
	'Rakúsy',
	'Zámutov',
	'Vlčany',
	'Jelšava',
	'Podolínec',
	'Rosina',
	'Huncovce',
	'Hranovnica',
	'Hruštín',
	'Nesluša',
	'Klenovec',
	'Topoľníky',
	'Dolná Súča',
	'Likavka',
	'Lozorno',
	'Nová ľubovňa',
	'Veľký Kýr',
	'Polomka',
	'Lužianky',
	'Richnava',
	'Vechec',
	'Oravské Veselé',
	'Liesek',
	'Mojmírovce',
	'Spišský Štiavnik',
	'Zvolenská Slatina',
	'Hliník nad Hronom',
	'Tekovské Lužany',
	'Šarišské Michaľany',
	'Podhorany',
	'Špačince',
	'Kokava nad Rimavicou',
	'Selice',
	'Jakubany',
	'Závod',
	'Pribeta',
	'Liptovská Lúžna',
	'Svätý Peter',
	'Staškov',
	'Nová Bystrica',
	'Horné Srnie',
	'Sečovská Polianka',
	'Veľké Kostoľany',
	'Pečovská Nová Ves',
	'Stará Bystrica',
	'Vyšné Raslavice',
	'Chynorany',
	'Trnovec nad Váhom',
	'Krásnohorské Podhradie',
	'Ivanka pri Nitre',
	'Vrakúň',
	'Miloslavov',
	'Košeca',
	'Vysoká nad Kysucou',
	'Veľké Brestovany',
	'Lehnice',
	'Zázrivá',
	'Čaklov',
	'Heľpa',
	'Topoľčianky',
	'Očová',
	'Ladce',
	'Kopčany',
	'Dolné Vestenice',
	'Zeleneč',
	'Veľký Biel',
	'Chtelnica',
	'Drahovce',
	'Moravské Lieskové',
	'Spišské Bystré',
	'Soľ',
	'Strečno',
	'Tomášov',
	'Veľká Mača',
	'Hrabušice',
	'Široké',
	'Stráne pod Tatrami',
	'Rozhanovce',
	'Spišský Štvrtok',
	'Svodín',
	'Viničné',
	'Papradno',
	'Solčany',
	'Liptovská Teplička',
	'Stakčín',
	'Moravany nad Váhom',
	'Sačurov',
	'Budmerice',
	'Žehra',
	'Batizovce',
	'Divina',
	'Važec',
	'Plavecký Štvrtok',
	'Chminianske Jakubovany',
	'Zlatná na Ostrove',
	'Pliešovce',
	'Oslany',
	'Lokca',
	'Kysucký Lieskovec',
	'Bučany',
	'Veľké Šúrovce',
	'Zemianska Olča',
	'Kamenica nad Cirochou',
	'Závadka nad Hronom',
	'Soblahov',
	'Klokočov',
	'Spišská Stará Ves',
	'Zubrohlava',
	'Boleráz',
	'Brodské',
	'Jaslovské Bohunice',
	'Zavar',
	'Hrnčiarovce nad Parnou',
	'Pruské',
	'Letanovce',
	'Svinia',
	'Diakovce',
	'Plešivec',
	'Drienovec',
	'Drietoma',
	'Spišská Teplica',
	'Dolná Krupá',
	'Cinobaňa',
	'Zborov nad Bystricou',
	'Streda nad Bodrogom',
	'Častá',
	'Kapušany',
	'Zbehy',
	'Krížová Ves',
	'Veľká Udiča',
	'Jablonica',
	'Drienov',
	'Madunice',
	'Lehota',
	'Výčapy-Opatovce',
	'Pohorelá',
	'Matúškovo',
	'Vojčice',
	'Jarovce',
	'Kalinovo',
	'Fintice',
	'Trhová Hradská',
	'Gbelce',
	'Zemné',
	'Selce',
	'Seňa',
	'Sihelné',
	'Brusno',
	'Čečejovce',
	'Východná',
	'Suchá nad Parnou',
	'Ostrovany',
	'Moravský Svätý Ján',
	'Valaská Belá',
	'Lisková',
	'Lysá pod Makytou',
	'Rimavská Seč',
	'Jelenec',
	'Váhovce',
	'Hliník',
	'Veľké Ripňany',
	'Nitrianske Hrnčiarovce',
	'Švedlar',
	'Bzince pod Javorinou',
	'Rišňovce',
	'Kozárovce',
	'Divín',
	'Hamuliakovo',
	'Lovinobaňa',
	'Marianka',
	'Pružina',
	'Bojná',
	'Spišské Tomášovce',
	'Víťaz',
	'Veľké Uherce',
	'Jarok',
	'Rabčice',
	'Dvorníky',
	'Horná Potôň',
	'Prašice',
	'Badín',
	'Kendice',
	'Majcichov',
	'Turie',
	'Kotešová',
	'Dolné Saliby',
	'Trhovište',
	'Strekov',
	'Vyšná Šuňava',
	'Petrovany',
	'Omšenie',
	'Toporec',
	'Imeľ',
	'Radošina',
	'Hermanovce',
	'Lemešany',
	'Olešná',
	'Nitrianske Rudno',
	'Dlhé nad Cirochou',
	'Ochodnica',
	'Bobrovec',
	'Margecany',
	'Kameničná',
	'Parchovany',
	'Michaľany',
	'Dolný Štál',
	'Dlhé Pole',
	'Horné Orešany',
	'Mužla',
	'Vikartovce',
	'Harichovce',
	'Jaklovce',
	'Horná Kráľová',
	'Dobrá Niva',
	'Banské',
	'Slovenská Ves',
	'Slavošovce',
	'Nižné Slovinky',
	'Veľké Lovce',
	'Pukanec',
	'Podolie',
	'Stráňavy',
	'Dechtice',
	'Lietavská Lúčka',
	'Ďurkov',
	'Zuberec',
	'Báhoň',
	'Hlinné',
	'Ludanice',
	'Bobrov',
	'Krížovany nad Dudváhom',
	'Nacina Ves',
	'Kolárovice',
	'Kamenica',
	'Vinné',
	'Bystričany',
	'Vidiná',
	'Dohňany',
	'Kráľová nad Váhom',
	'Pusté Úľany',
	'Nemecká',
	'Blatné',
	'Zemianske Kostoľany',
	'Mníšek nad Hnilcom',
	'Leles',
	'Diviacka Nová Ves',
	'Zákopčie',
	'Jacovce',
	'Štvrtok na Ostrove',
	'Sekule',
	'Golianovo',
	'Diviaky nad Nitricou',
	'Sebedražie',
	'Lietavská Svinná',
	'Šintava',
	'Pohronská Polhora',
	'Dulovce',
	'Geča',
	'Žabokreky nad Nitrou',
	'Makov',
	'Kriváň',
	'Dolné Sľažany',
	'Valča',
	'Žihárec',
	'Orechová Potôň',
	'Zemplínska Teplica',
	'Vydrany',
	'Krušovce',
	'Čereňany',
	'Janovce',
	'Lazany',
	'Kuchyňa',
	'Nižná Myšľa',
	'Tomášikovo',
	'Malý Šariš',
	'Košúty',
	'Halič',
	'Klátova Nová Ves',
	'Červeník',
	'Štefanov',
	'Borský Svätý Jur',
	'Nižný Hrabovec',
	'Ožďany',
	'Plavnica',
	'Iža',
	'Nová Lesná',
	'Ružindol',
	'Liptovská Osada',
	'Bešeňov',
	'Breza',
	'Čierny Brod',
	'Chlebnice',
	'Vígľaš',
	'Horný Vadičov',
	'Veľké Šarovce',
	'Horná Štubňa',
	'Kovarce',
	'Studienka',
	'Dolný Hričov',
	'Žaškov',
	'Dubník',
	'Hodejov',
	'Modrý Kameň',
	'Župčany',
	'Mostová',
	'Spišský Hrhov',
	'Kláštor pod Znievom',
	'Malcov',
	'Veľké Blahovo',
	'Hrań',
	'Kolíňany',
	'Veľký Cetín',
	'Domaniža',
	'Malá Ida',
	'Hviezdoslavov',
	'Bidovce',
	'Kluknava',
	'Svinná',
	'Poniky',
	'Sološnica',
	'Opatovce nad Nitrou',
	'Jahodná',
	'Trstené pri Hornáde',
	'Bolešov',
	'Kočovce',
	'Trakovice',
	'Dolný Ohaj',
	'Radzovce',
	'Plášťovce',
	'Ražňany',
	'Torysa',
	'Liptovské Revúce',
	'Dolná Streda',
	'Švábovce',
	'Krasňany',
	'Nižný Hrušov',
	'Konská',
	'Telgárt',
	'Vrbov',
	'Krajné',
	'Budkovce',
	'Štítnik',
	'Kajal',
	'Úľany nad Žitavou',
	'Vrbovce',
	'Komjatná',
	'Voderady',
	'Malčice',
	'Obyce',
	'Vavrečka',
	'Reca',
	'Uhrovec',
	'Veľký Lapáš',
	'Ruskov',
	'Málinec',
	'Malženice',
	'Sobotište',
	'Bystrička',
	'Nižný Žipov',
	'Okoličná na Ostrove',
	'Radola',
	'Hrochoť',
	'Častkovce',
	'Lietava',
	'Tovarníky',
	'Slanec',
	'Prečín',
	'Drahňov',
	'Dubovica',
	'Andovce',
	'Hontianske Nemce',
	'Veľké Ludince',
	'Hyby',
	'Varhaňovce',
	'Rybany',
	'Kysak',
	'Hniezdne',
	'Sielnica',
	'Starý Tekov',
	'Bíňa',
	'Babín',
	'Trstín',
	'Kamenín',
	'Čunovo',
	'Veľké Trakany',
	'Somotor',
	'Lubina',
	'Suchá Hora',
	'Kvetoslavov',
	'Hronské Kľačany',
	'Helcmanovce',
	'Bušince',
	'Preseľany',
	'Ždaňa',
	'Dudince',
	'Sedliská',
	'Vyšné Ružbachy',
	'Bojničky',
	'Šarišské Jastrabie',
	'Bohdanovce nad Trnavou',
	'Dolná Mariková',
	'Dlhá nad Oravou',
	'Kútniky',
	'Biel',
	'Urmince',
	'Chrenovec-Brusno',
	'Bošáca',
	'Veľký Slavkov',
	'Chotín',
	'Habovka',
	'Medzibrod',
	'Gánovce',
	'Horná Streda',
	'Dlhé Klčovo',
	'Dolná Tižina',
	'Semerovo',
	'Gbelany',
	'Ždiar',
	'Čierna Voda',
	'Skačany',
	'Nenince',
	'Klasov',
	'Beckov',
	'Vlčkovce',
	'Predmier',
	'Brzotín',
	'Michalová',
	'Žirany',
	'Modrany',
	'Istebné',
	'Oravský Podzámok',
	'Mokrance',
	'Nová Ves nad Žitavou',
	'Hencovce',
	'Trebatice',
	'Budča',
	'Kostolné Kračany',
	'Rimavské Janovce',
	'Sverepec',
	'Mošovce',
	'Sokoľany',
	'Kolačkov',
	'Kamenica nad Hronom',
	'Farná',
	'Lutila',
	'Liptovský Svätý Peter',
	'Svätoplukovo',
	'Ohrady',
	'Podvysoká',
	'Košťany nad Turcom',
	'Rožkovany',
	'Veľký Grob',
	'Krnča',
	'Predajná',
	'Mirkovce',
	'Tulčík',
	'Vištuk',
	'Mojzesovo',
	'Pribylina',
	'Tatranská Lomnica',
	'Pravenec',
	'Vlkanová',
	'Brekov',
	'Kalinkovo',
	'Vitanová',
	'Lubeník',
	'Pozdišovce',
	'Čičava',
	'Sokolovce',
	'Gemerská Horka',
	'Čáry',
	'Šíd',
	'Dolné Orešany',
	'Čirč',
	'Chminianska Nová Ves',
	'Terňa',
	'Nové Sady',
	'Kolta',
	'Košické Olšany',
	'Závažná Poruba',
	'Podbiel',
	'Veličná',
	'Šumiac',
	'Číčov',
	'Spišský Hrušov',
	'Dojč',
	'Cigeľ',
	'Žemberovce',
	'Družstevná pri Hornáde',
	'Nižná Slaná',
	'Pohronský Ruskov',
	'Sirk',
	'Želovce',
	'Veľké Dvorníky',
	'Žabokreky',
	'Výborná',
	'Udavské',
	'Liešťany',
	'Trnavá Hora',
	'Trenčianske Jastrabie',
	'Boťany',
	'Partizánska ľupča',
	'Bajč',
	'Krivany',
	'Kračúnovce',
	'Nitrianska Blatnica',
	'Hostie',
	'Jurské',
	'Tekovská Breznica',
	'Muráň',
	'Vydrník',
	'Nána',
	'Horný Bar',
	'Ruská Nová Ves',
	'Dolné Kočkovce',
	'Sebechleby',
	'Hronec',
	'Kokšov-Bakša',
	'Mnichova Lehota',
	'Buzica',
	'Lazy pod Makytou',
	'Rohovce',
	'Vyšný Žipov',
	'Veselé',
	'Nitrianske Sučany',
	'Tužina',
	'Čechynce',
	'Budimír',
	'Sokolce',
	'Ráztočno',
	'Vyhne',
	'Mýtna',
	'Hvozdnica',
	'Cejkov',
	'Brvnište',
	'Svätý Anton',
	'Vyšná Šebastová',
	'Sokoľ',
	'Rajecká Lesná',
	'Jamník',
	'Lastomír',
	'Lastovce',
	'Šarišské Dravce',
	'Svederník',
	'Veľký Blh',
	'Žehňa',
	'Čalovec',
	'Jasenie',
	'Liptovská Porúbka',
	'Kechnec',
	'Liptovská Štiavnica',
	'Dunajov',
	'Stankovany',
	'Povina',
	'Hajnáčka',
	'Dolné Obdokovce',
	'Zemplínske Hradište',
	'Čakajovce',
	'Čataj',
	'Lukáčovce',
	'Obid',
	'Čilizská Radvaň',
	'Pobedim',
	'Katlovce',
	'Beňuš',
	'Zvolenské Nemce',
	'Jasová',
	'Bzovík',
	'Bátovce',
	'Borša',
	'Kráľovce',
	'Fričovce',
	'Stará Kremnička',
	'Opoj',
	'Lenartov',
	'Vtáčkovce',
	'Vŕbnica',
	'Búč',
	'Kurima',
	'Tureň',
	'Malé Dvorníky',
	'Moča',
	'Hažlín',
	'Šajdíkove Humence',
	'Lakšárska Nová Ves',
	'Jasenica',
	'Machulince',
	'Skároš',
	'Malý Horeš',
	'Krpeľany',
	'Bohdanovce',
	'Koš',
	'Kráľov Brod',
	'Slovenské Nové Mesto',
	'Kľušov',
	'Baka',
	'Malachov',
	'Hrhov',
	'Podtureň',
	'Veľká Lehota',
	'Kľačno',
	'Príbovce',
	'Dulova Ves',
	'Kľačany',
	'Mojš',
	'Čenkovce',
	'Ďurčiná',
	'Olcnava',
	'Hubová',
	'Horná Poruba',
	'Čebovce',
	'Hrčeľ',
	'Petrova Ves',
	'Ratnovce',
	'Malé Trakany',
	'Demjata',
	'Pohranice',
	'Liptovský Ján',
	'Veľké Orvište',
	'Hostice',
	'Tekovské Nemce',
	'Zamarovce',
	'Rakovec nad Ondavou',
	'Kálnica',
	'Veľký Horeš',
	'Trávnica',
	'Kamenný Most',
	'Černík',
	'Kráľovičove Kračany',
	'Ladomirová',
	'Dolná Strehová',
	'Malý Slavkov',
	'Moravany',
	'Sedlice',
	'Kunerad',
	'Petrovce nad Laborcom',
	'Hertník',
	'Hladovka',
	'Abrahám',
	'Nededza',
	'Smolník',
	'Jablonec',
	'Divinka',
	'Jelšovce',
	'Stožok',
	'Borovce',
	'Chmeľov',
	'Kružlov',
	'Liptovská Teplá',
	'Dubovany',
	'Chmeľnica',
	'Ludrová',
	'Stará Lesná',
	'Novosad',
	'Snežnica',
	'Volkovce',
	'Nemčice',
	'Záhradné',
	'Jablonov',
	'Prievaly',
	'Selec',
	'Richvald',
	'Lodno',
	'Komárno',
];
